import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import RootProvider from "@/components/proviers/RootProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "OpenHiring",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} antialiased`}>
                <RootProvider>{children}</RootProvider>
            </body>
        </html>
    );
}
